name = "Flou"
grammar = "flou-grammar"
path_suffixes = ["f"]
line_comments = ["//"]

brackets = [
    { start = "'", end = "'", close = true, newline = false, not_in = [
        "string",
    ] },
    { start = "(", end = ")", close = true, newline = false, not_in = [
        "string",
    ] },
    { start = "{", end = "}", close = true, newline = false, not_in = [
        "string",
    ] },
    { start = "[", end = "]", close = true, newline = false, not_in = [
        "string",
    ] },
]

[grammars.flou]
repository = "https://github.com/gleam-lang/tree-sitter-gleam"
rev = "58b7cac8fc14c92b0677c542610d8738c373fa81"
